// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SabayNew.Dal;

public partial class Content
{
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public string Tiltle { get; set; }

    public string ImageUrl { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Category Category { get; set; }
}